### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by net2cn** [bjason/163MusicToSpotify#15]
I had this issue using Python 3.5.5 on Windows 10 1803. However, I managed to find a possible solution to this.

Here's the traceback:

Traceback (most recent call last):
  File "AlternativeMethodForPy3.py", line 36, in <module>
    data = json.loads(response)
  File "C:\Users\*****\Anaconda3\envs\**********\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

Can be solved by adding ".decode('utf-8')" at the end of line 35.
`	response = urllib.request.urlopen(req, encodedContent).read().decode('utf-8')`

**Comment by bjason** [comment]
thank you! I have updated the file using the code you provided
