### ISSUE TITLE
KeyError?

### ISSUE THREAD

**Issue by ForkOnTheLeft** [bjason/163MusicToSpotify#16]
请问怎么解决?

C:\Users\sy21d\Downloads\163MusicToSpotify-master>py AlternativeMethodForPy3.py
===== Get tracks of your 163 playlist =====
Enter the playlist id (Enter ? to get help):318339843
Traceback (most recent call last):
  File "AlternativeMethodForPy3.py", line 48, in <module>
    tracks = body["songs"]
KeyError: 'songs'

**Comment by bjason** [comment]
这个歌单并没有歌曲呀~
https://music.163.com/#/playlist?id=318339843

**Comment by ForkOnTheLeft** [comment]
> 这个歌单并没有歌曲呀~
> https://music.163.com/#/playlist?id=318339843

不好意思哈哈哈哈哈 是我自己打错id了 谢谢你!
