### ISSUE TITLE
网易云导出问题

### ISSUE THREAD

**Issue by Dijion** [bjason/163MusicToSpotify#2]
用python运行的时候 出现这样

> Traceback (most recent call last):
>   File "\\Mac\Home\Desktop\163MusicToSpotify-master\t.py", line 7, in <module>
>     response = urllib.urlopen(url)
> AttributeError: module 'urllib' has no attribute 'urlopen'
> 

请问如何解决

**Comment by bjason** [comment]
.urlopen是python 2.x的用法 如果您电脑上安装的是python 3 请将该行改为：
with urllib.request.urlopen("http://www.python.org") as url:
    s = url.read()

**Comment by bjason** [comment]
.urlopen是python 2.x的用法 如果您电脑上安装的是python 3 请将该行改为：

```
with urllib.request.urlopen(url) as url:
    s = url.read()
```

**Comment by bjason** [comment]
这是因为您电脑上安装的是python 3
我已经更改了部分代码 应该可以支持python 3了
请您重新下载t.py文件并依照要求走一遍哦

**Comment by Dijion** [comment]
好像又出现了什么奇怪的东西。。。

> Traceback (most recent call last):
>   File "/Users/jiayuanyan/Downloads/163MusicToSpotify-master 2/t.py", line 34, in <module>
>     file.write(output.encode('utf8'))
> TypeError: write() argument must be str, not bytes

**Comment by bjason** [comment]
呃还是python 3的问题呃 我又改了一下
因为我电脑上装的是python 2所以不能测试在py3上的情况了……
所以请见谅

**Comment by Dijion** [comment]
好 我去装一下python2

**Comment by bjason** [comment]
你先试一试我改的（我刚刚又改了几行）？如果不行我再改（真的很苦

**Comment by Dijion** [comment]
好了好了！！谢谢谢谢

**Comment by zorroscell** [comment]
t.py这个文件怎么找不到了呢？谢谢

**Comment by bjason** [comment]
忘记修改readme了不好意思
如果电脑上安装了python2请下载python2.py
否则请下载python3.py
随后步骤不变
