### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Jassin722** [bjason/163MusicToSpotify#21]
Traceback (most recent call last):
  File "AlternativeMethodForPy2.py", line 57, in <module>
    with open(playlistName + ".txt", "w", encoding="utf-8") as file:
TypeError: 'encoding' is an invalid keyword argument for this function

怎么办呢

**Comment by bjason** [comment]
try https://github.com/bjason/163MusicToSpotify/blob/master/altPy2 please

**Comment by Jassin722** [comment]
还有一点问题
 File "/Users/linjiaxin/163MusicToSpotify/AlternativeMethodForPy2.py", line 35
    req = urllib2.Request(reqUrl)
    ^
IndentationError: unexpected indent

**Comment by Jassin722** [comment]
还有一点问题 
File "AlternativeMethodForPy2.py", line 35
    req = urllib2.Request(reqUrl)
    ^
IndentationError: unexpected indent

**Comment by bjason** [comment]
> req = urllib2.Request(reqUrl)
> ^
> IndentationError: unexpected indent

我觉得这个不是普遍的问题 tab/空格混用的问题
可以尝试搜索4个空格全部替换为tab
或者在命令行尝试
```
expand -t 4 AlternativeMethodForPy2.py > fixed_script.py
```
https://stackoverflow.com/questions/8634700/python-indentationerror-unexpected-indent

**Comment by bjason** [comment]
可以尝试@yueyericardo提供的web实现：https://yyrcd.com/2018/11/14/n2s-zh/ 。

**Comment by Jassin722** [comment]
> 可以尝试@yueyericardo提供的web实现：https://yyrcd.com/2018/11/14/n2s-zh/ 。

好的，谢谢
