### ISSUE TITLE
Web 实现 yyrcd.com/n2s

### ISSUE THREAD

**Issue by yueyericardo** [bjason/163MusicToSpotify#22]
https://yyrcd.com/2018/11/14/n2s-zh/
根据作者的代码，上个学期做了web实现，用起来会比脚本方便点。

repo地址：https://github.com/yueyericardo/Netease-to-Youtube-or-Spotify

**Comment by bjason** [comment]
感谢~我添加到readme可以嘛

**Comment by yueyericardo** [comment]
嗯嗯，可以的～
