### ISSUE TITLE
这个API只输出第一个歌曲的信息

### ISSUE THREAD

**Issue by serenadewy** [bjason/163MusicToSpotify#6]
运行了一下代码以后发现只输出了第一首歌的信息，所以我就输出了一下那个dict文件，发现这个API只有第一首歌，该怎么解决呢？

**Comment by bjason** [comment]
……我试了一下好像是只返回了一首哎…可能是网易云音乐更新API了吧 我去研究研究…

**Comment by izhujialiang** [comment]
之前的确只能返回列表第一首歌，现在能正确识别了，很神奇

**Comment by serenadewy** [comment]
真的成功了。。估计是网易云对他的API给进行了调整吧，终于可以导歌出来了

**Comment by bjason** [comment]
噗 所以说明有时候解决问题的方法就是不去管他……谢谢各位的劳心了哈哈哈哈
